# 服务器配置
server:
  port: "7895"
  mode: "release"
  read_timeout: 10
  write_timeout: 10
  idle_timeout: 60
  proxy:
    enabled: false
    trusted_proxies: ["127.0.0.1", "::1"]
    real_ip_header: "X-Forwarded-For"

# API配置
api:
  prefix: "/api/v1"
  allowed_origins: "*"

ipv4database:
  dbpath: "./ipdata/ipv4.xdb"
  version: "xdb.IPv4"
  
ipv6database:
  dbpath: "./ipdata/ipv6.xdb"
  version: "xdb.IPv6"


# 用户配置
user:
  api_key_length: 32